name: Coding Style Checks

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ci:
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.os }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-versions: ['7.2', '7.3', '7.4', '8.0']
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpize
          coverage: none

      - name: Run Coding Style Checks
        run:
          composer cs-check
